name: Deploy Databricks Bundle (dev)

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
    steps:
      - name: Echo Environment
        run: echo "Deploying to DEV environment"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main
      - name: Validate Databricks Asset Bundle
        run: databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
      - name: Deploy Databricks Asset Bundle
        run: databricks bundle deploy --target dev --force-lock
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
      - name: Run Pytest
        run: databricks bundle run pytest --target dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
      - name: Run Smoke Test
        run: databricks bundle run smoke_test --target dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
